idf_component_register(SRCS "cytrons.c" 
			    "encoders.c" 
			    "limit_switches.c" 
			    "uart.c" 
			    "current_sensors.c" 
			    "servos.c"
			    "pid.c"
			    "smart_servos.c"
			    "leds.c"
			    "s_curve.c"
                    INCLUDE_DIRS "include"
		    REQUIRES driver esp_timer led_strip)
